# Generated by Django 2.1.7 on 2019-03-18 03:06

from django.db import migrations, models
import personnel_management.apps.branches.AS3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='facade_image',
            field=models.ImageField(blank=True, null=True, storage=personnel_management.apps.branches.AS3_storage.FacadeImageStorage, upload_to=''),
        ),
    ]
